name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push되면 배포 시작
  workflow_dispatch:  # 수동 트리거 옵션 추가

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Set environment variables
        run: echo "CUSDIS_APP_ID=${{ secrets.CUSDIS_APP_ID }}" >> $GITHUB_ENV

      - name: Build the site
        run: hugo --minify

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # gh-pages 브랜치로 배포
